- _target_: cytodata_aics.latent_walk.LatentWalk
  embedding_dim: ${model.latent_dim}
  x_label: "image"
  spharm_cols_filter:
    startswith: "dna_"
    contains: "shcoeff"
  latent_walk_range: [-2.0, -1.5, -1.0, -0.5,  0.0,  0.5,  1.0,  1.5,  2.0]
  input_mode: "image"
  compute_features: True